#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www//html/roa_404.html
sed -i "/listen 80 default_server;/a error_page 404 /roa_404.html;" /etc/nginx/sites-available/default
service nginx restart
