#!/usr/bin/env bash
# Install and configure HAproxy on your server
apt-get -y update
apt-get -y install haproxy
sed -i '/errorfile 504/a listen yon_server' /etc/haproxy/haproxy.cfg
sed -i '/listen yon_server/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         balance roundrobin' /etc/haproxy/haproxy.cfg
sed -i '/balance roundrobin/a         server 4540-web-01 107.22.30.13:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 4540-web-01 107.22.30.13:80 check/a         server 4540-web-02 34.233.122.76:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
