#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# for the 9th iteration displays Best School and then Hi on a new line
i=0
while (( i < 10 ))
do
    echo ""Best School""
    if (( i == 8 ))
    then
        echo "Hi"
    fi
    i=$((i+1))
done
